## Freedom configuration File.

# Servers name
server-name: ImmaFreedom

# Motd that displays during a ping on the server list
# %servername% is the String above
motd: "%servername% - Free OP 1.9"

# Ban url, more info below
banurl: http://example.com

# Can a user appeal from a ban (true or false), will return message above if true
canappeal: true

# Limit the access of the server to admins only (true or false)
lockdown-enabled: false

# Commands that nobody can do, blocks aliases automatically when real command is blocked {include a / before the command for worldedit commands}
Blocked-Cmds:
  - time
  - gamemode
  - pardon
  - ban-ip
  - pardon-ip
  - toggledownfall
  - effect
  - enderchest
  - spreadplayers
  - execute
  - blockdata
  - clearhistory
  - save-all
  - save-on
  - save-off

# Commands that only superadmins and higher can do, blocks aliases automatically when real command is blocked {include a / before the command for worldedit commands}
SA-Commands:
  - kick
  - co
  - socialspy
  - kill
  - /generate
  - /
  - superpickaxe
  - brush
  - size
  - /mask
  - mat
  - /butcher
  - scoreboard
  - setspawn
  - /snow
  - tellraw
  - forestgen
  - setidletimeout
  - mail sendall
  - eco reset
  - mask
  - gmask
  - lrbuild
  - defaultgamemode
  - reload
  - title
  - worldborder
  - weather
  - tpall
  - setblock
  - green
  - gamerule
  - togglejail